# Generated by Django 2.1 on 2019-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('nickName', models.CharField(max_length=30)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('changeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
